export const Featured = [
  {
    Author: "Angel Andreychev",
    thumbnail: "https://i1.chainbulletin.com/img/2020/10/693.jpg",
    Date: "October 28, 2020",
    Title: "Telos Task Launches In Beta, Announces Token Pre-Sale",
    link: "https://chainbulletin.com/telos-task-launches-in-beta-announces-token-pre-sale/",
  },
  {
    Author: "MARIE HUILLET",
    thumbnail: "https://images.cointelegraph.com/images/717_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS91cGxvYWRzLzIwMjAtMTAvM2Y4Nzc2NzctMzBiYS00N2Y5LTk1ODEtNTUxYTdmZjNhNjZiLmpwZw==.jpg",
    Date: "OCT 28, 2020",
    Title: "Telos launches new gig economy platform on the blockchain",
    link: "https://cointelegraph.com/news/telos-launches-new-gig-economy-platform-on-the-blockchain",
  },
  {
    Author: "Fycee",
    thumbnail: "https://s2.discussions.app/v1/api/upload/file/1619280896235.png",
    Date: "Apr 24, 2021",
    Title: "Telostask is coming to T-starter",
    link: "https://discussions.app/u/Fycee",
  },
  {
    Author: "dappradar",
    thumbnail: "https://dashboard-assets.dappradar.com/document/7136/telostask-dapp-marketplaces-telos-image3-500x315_b38152b99945caaeea76931f2c0abe8f.png",
    Date: "",
    Title: "TelosTask statistics",
    link: "https://dappradar.com/telos/marketplaces/telostask",
  },
  {
    Author: "airdropalert",
    thumbnail: "https://cdn.airdropalert.com/images/metadata/telostask22.jpg",
    Date: "",
    Title: "TelosTask (TASK) Airdrop",
    link: "https://airdropalert.com/telostask-airdrop",
  },
  {
    Author: "Dapp expert",
    thumbnail: "https://old.dapp.expert/wp-content/uploads/2021/11/TelosTask.jpg",
    Date: "",
    Title: "Description of the TelosTask nft chain",
    link: "https://dapp.expert/dapp/en-tlos-telostask-",
  },
  {
    Author: "eosgo",
    thumbnail: "https://www.eosgo.io/img/logo.png",
    Date: "",
    Title: "TASK token",
    link: "https://www.eosgo.io/marketcap/task-telostaskapp",
  },
  {
    Author: "Ellsa Milana",
    thumbnail: "https://cdn.publish0x.com/prod/fs/images/6b8f1b5b5ba4a1dff46872d662fca1e2eed087c7af7ea7d435db9fafc53471df.jpeg",
    Date: " 27 Oct 2020",
    Title: "You'll get 50 Task ($50) for completing all tasks ",
    link: "https://www.publish0x.com/make-money-online-just-got-real/telos-task-airdrop-youll-get-50-task-dollar-50-for-completin-xejwewe",
  },
  {
    Author: "ohn Flores",
    thumbnail: "",
    Date: "February 21, 2022",
    Title: "Be a part of our story (Partner or join us) #blockchain #telos",
    link: "https://cyberbump.net/be-a-part-of-our-story-partner-or-join-us-blockchain-telos/",
  },
];
